apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-app
  namespace: default # Update if using a custom namespace
  labels:
    app: angular-app
spec:
  replicas: 2 # Adjust based on your scaling requirements
  selector:
    matchLabels:
      app: angular-app
  template:
    metadata:
      labels:
        app: angular-app
    spec:
      containers:
        - name: angular-app
          image: LOCATION-docker.pkg.dev/PROJECT_ID/REPOSITORY/IMAGE:TAG # Replace with GitHub Actions
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20

---
apiVersion: v1
kind: Service
metadata:
  name: internal-lb
  annotations:
    cloud.google.com/load-balancer-type: "Internal"  # Specifies an internal load balancer
spec:
  selector:
    app: angular-app
  ports:
    - protocol: TCP
      port: 80         # Port exposed by the LoadBalancer
      targetPort: 8080 # Port of the application container
  type: LoadBalancer  # Defines the service as a LoadBalancer


