apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-app
  namespace: default # Update if using a custom namespace
  labels:
    app: angular-app
spec:
  replicas: 1 # Adjust based on your scaling requirements
  selector:
    matchLabels:
      app: angular-app
  template:
    metadata:
      labels:
        app: angular-app
    spec:
      containers:
        - name: angular-app
          image: LOCATION-docker.pkg.dev/PROJECT_ID/REPOSITORY/IMAGE:TAG # Replace with GitHub Actions
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20

---
apiVersion: v1
kind: Service
metadata:
  name: external-lb
  annotations:
    cloud.google.com/neg: '{"exposed_ports":{"80":{"name":"external-lb-neg"}}}' # Optional for better GKE integration
spec:
  selector:
    app: angular-app # Match the labels of the pod you want to expose
  ports:
    - protocol: TCP
      port: 80         # Port exposed by the LoadBalancer to the internet
      targetPort: 80   # Port on the pod serving the application
  type: LoadBalancer



