name: Build, Push, and Update Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      # Checkout Source Code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Login to Docker Hub
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      # Get timestamp
      - name: Get Timestamp
        run: echo "TIMESTAMP=$(date +%H%M%S)" >> $GITHUB_ENV
        shell: bash

      # Build the Docker Image
      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/photos:$TIMESTAMP .

      # Push Docker Image to Docker Hub
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/photos:$TIMESTAMP

      # Update deploy.yaml with new image tag
      - name: Update Deployment YAML
        run: |
          sed -i "s|image: .*|image: ${{ secrets.DOCKERHUB_USERNAME }}/photos:$TIMESTAMP|g" k8s/deploy.yaml
          cat k8s/deploy.yaml

      # Commit and Push Changes
      - name: Commit and Push Updated Deployment File
        run: |
          git config --global user.email "bot@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Update photos image to $TIMESTAMP"
          git push origin main
