name: Deploy Angular App to GKE

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT }}
  GAR_LOCATION: europe-west1
  GKE_CLUSTER:  purvesh-angular-cluster
  GKE_REGION: europe-west1
  REPOSITORY: purvesh-angular-frontend
  IMAGE: basic-gallery-ng

jobs:
  build-publish-deploy:
    name: Build, Publish, and Deploy Angular App
    runs-on: self-hosted

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Docker configuration
        run: |-
          gcloud auth activate-service-account --key-file=/home/aslairline_gcp/.docker/config.json

      - name: Build Docker Image
        run: |
          docker build \
            --tag "$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:$GITHUB_SHA" \
            --build-arg GITHUB_SHA="$GITHUB_SHA" \
            --build-arg GITHUB_REF="$GITHUB_REF" \
            .

      - name: Push Docker Image to Artifact Registry
        run: |
          docker push "$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:$GITHUB_SHA"

      - name: Cleanup Docker Image from Workspace
        run: |
          docker rmi "$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:$GITHUB_SHA"
          

      - name: Configure kubectl
        uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_REGION }}

      - name: Deploy to GKE
        run: |
          sed -i "s|LOCATION-docker.pkg.dev/PROJECT_ID/REPOSITORY/IMAGE:TAG|$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:$GITHUB_SHA|g" k8s/deploy.yaml
          kubectl apply -f k8s/deploy.yaml
          kubectl rollout status deploy/angular-app --namespace=default
