name: Deploy Angular App to GKE

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT }}
  GAR_LOCATION: europe-west1
  GKE_CLUSTER: purvesh-angular-cluster
  GKE_REGION: europe-west1
  GCLOUD_PROJECT: asl-pocs
  REPOSITORY: purvesh-angular-frontend
  IMAGE: purvesh-gallery-ng

jobs:
  authenticate:
    name: Authenticate to Google Cloud
    runs-on: self-hosted
    steps:
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Docker configuration
        run: |-
          echo '${{ secrets.GCP_CREDENTIALS }}' > gcp-credentials.json
          gcloud auth activate-service-account --key-file=gcp-credentials.json
          gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://europe-west1-docker.pkg.dev

  build:
    name: Build Docker Image
    runs-on: self-hosted
    needs: authenticate
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          docker build \
            --tag "$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:$GITHUB_SHA" \
            --build-arg GITHUB_SHA="$GITHUB_SHA" \
            --build-arg GITHUB_REF="$GITHUB_REF" \
            .

  push:
    name: Push Docker Image to Artifact Registry
    runs-on: self-hosted
    needs: build
    steps:
      - name: Push Docker Image to Artifact Registry
        run: |-
          gcloud auth list
          echo '${{ secrets.GCP_CREDENTIALS }}' > gcp-credentials.json
          docker login -u _json_key --password-stdin https://$GAR_LOCATION-docker.pkg.dev < gcp-credentials.json
          docker push "$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:$GITHUB_SHA"

      - name: Cleanup Docker Image from Workspace
        run: |
          docker rmi "$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:$GITHUB_SHA"

  deploy:
    name: Deploy to GKE
    runs-on: self-hosted
    needs: push
    steps:
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
          
      - name: Configure kubectl
        run: |-
          gcloud auth list
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/
      
      - name: Authenticate with GKE Cluster
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_REGION }}
            
        

      - name: Deploy to GKE
        run: |
          gcloud auth list
          sed -i "s|LOCATION-docker.pkg.dev/PROJECT_ID/REPOSITORY/IMAGE:TAG|$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:$GITHUB_SHA|g" k8s/deploy.yaml
          kubectl apply -f k8s/deploy.yaml
          kubectl rollout status deploy/angular-app --namespace=default
